// FolderDrafts.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing folder-drafts.svg overwrites this file.
import type { SVGProps } from "react";

export default function FolderDrafts(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-folder-drafts" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 8h8m-8 4h22M5 16h6m-6 4h12m-3-4h13m-6 4h6M5 24h2m4 0h4"/></svg>
    );
}
