// Activity.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing activity.svg overwrites this file.
import type { SVGProps } from "react";

export default function Activity(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-activity" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 16h6l4-11l6 22l4-11h6"/></svg>
    );
}
