// TextLeft.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing text-left.svg overwrites this file.
import type { SVGProps } from "react";

export default function TextLeft(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-text-left" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 7h22M5 13h14M5 19h22M5 25h14"/></svg>
    );
}
