// Add.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing add.svg overwrites this file.
import type { SVGProps } from "react";

export default function Add(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-add" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 25V7m-9 9h18"/></svg>
    );
}
