// Queue.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing queue.svg overwrites this file.
import type { SVGProps } from "react";

export default function Queue(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-queue" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M23 5v8m-4-4h8M7 9.731V24.27c0 1.508 1.753 2.293 2.83 1.266l7.632-7.269a1.76 1.76 0 0 0 0-2.532L9.83 8.465C8.753 7.44 7 8.223 7 9.731Z"/></svg>
    );
}
