// ChevronLeft.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing chevron-left.svg overwrites this file.
import type { SVGProps } from "react";

export default function ChevronLeft(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-chevron-left" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M20 6L10 16l10 10"/></svg>
    );
}
