// Mute.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing mute.svg overwrites this file.
import type { SVGProps } from "react";

export default function Mute(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-mute" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.5 21H8a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1h7l6.586-6.586C22.846 3.154 25 4.047 25 5.828V6m0 8.5v11.672c0 1.781-2.154 2.674-3.414 1.414L17 23M7 28L29 6"/></svg>
    );
}
