// Alt.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing alt.svg overwrites this file.
import type { SVGProps } from "react";

export default function Alt(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-alt" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M5 9h5.485a1 1 0 0 1 .814.419l9.402 13.162a1 1 0 0 0 .814.419H27M21 9h6"/></svg>
    );
}
