// settings.ts -- GENERATED by automation/icons/indexIcons.mjs
// `id` is intentionally blank: no db row exists yet. Whatever writes the row
// fills it in. `folder` is the folder NAME only -- the paths map holds where.
export const settings = {
    name: "arrow-up-circle",
    folder: "ArrowUpCircle",
    file_name: "arrow-up-circle.svg",
    id: "",
};

export default settings;
