// Send.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing send.svg overwrites this file.
import type { SVGProps } from "react";

export default function Send(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-send" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M29 3L3 15l12 2.5M29 3L19 29l-4-11.5M29 3L15 17.5"/></svg>
    );
}
