// Phone.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing phone.svg overwrites this file.
import type { SVGProps } from "react";

export default function Phone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-phone" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 25h2M11 3h10a2 2 0 0 1 2 2v22a2 2 0 0 1-2 2H11a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2"/></svg>
    );
}
