// InlineDown.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing inline-down.svg overwrites this file.
import type { SVGProps } from "react";

export default function InlineDown(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-inline-down" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m8 13l8 8l8-8"/></svg>
    );
}
