// Chat.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing chat.svg overwrites this file.
import type { SVGProps } from "react";

export default function Chat(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-chat" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"><path d="M25 5H7a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h11l6 4v-4h1a4 4 0 0 0 4-4V9a4 4 0 0 0-4-4"/><path d="M10 15a1 1 0 1 1-2 0a1 1 0 0 1 2 0m6 0a1 1 0 1 1-2 0a1 1 0 0 1 2 0m6 0a1 1 0 1 1-2 0a1 1 0 0 1 2 0"/></g></svg>
    );
}
