// FolderTrash.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing folder-trash.svg overwrites this file.
import type { SVGProps } from "react";

export default function FolderTrash(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-folder-trash" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M27 8c0 1.657-4.925 3-11 3S5 9.657 5 8m22 0c0-1.657-4.925-3-11-3S5 6.343 5 8m22 0l-3 18s-1 2-8 2s-8-2-8-2L5 8m13.5 8.5l-5 5m0-5l5 5"/></svg>
    );
}
