// FolderList.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing folder-list.svg overwrites this file.
import type { SVGProps } from "react";

export default function FolderList(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-folder-list" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M12 15h8m-8 4h8m8 5V11c0-1.105-.892-2-1.997-2H17c-2 0-2-3-5-3H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h20a2 2 0 0 0 2-2Z"/></svg>
    );
}
