// Info.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing info.svg overwrites this file.
import type { SVGProps } from "react";

export default function Info(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-info" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><mask id="SVGwjo0bdvJ" fill="#fff"><path d="M17.5 9.5a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0"/></mask><g fill="none" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d="M15 14h1v9h1m12-7a13 13 0 1 1-26 0a13 13 0 0 1 26 0"/><path fill="currentColor" d="M17.5 9.5a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0Z" mask="url(#SVGwjo0bdvJ)"/></g></svg>
    );
}
