// InboxAdd.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing inbox-add.svg overwrites this file.
import type { SVGProps } from "react";

export default function InboxAdd(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-inbox-add" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 27H8c-1.5 0-3-1.5-3-3v-8m0 0h5.5s1 3.5 5.5 3.5s5.5-3.5 5.5-3.5H27L23 5H9zm20 12v-8m-4 4h8"/></svg>
    );
}
