// Play.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing play.svg overwrites this file.
import type { SVGProps } from "react";

export default function Play(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-play" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 24.414V7.586c0-1.746 2.081-2.653 3.36-1.465l9.062 8.413a2 2 0 0 1 0 2.932l-9.061 8.413C13.08 27.067 11 26.16 11 24.414"/></svg>
    );
}
