// Command.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing command.svg overwrites this file.
import type { SVGProps } from "react";

export default function Command(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-command" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeWidth="2" d="M19 19v4a4 4 0 1 0 4-4zm0 0v-6m0 6h-6m6-6V9a4 4 0 1 1 4 4zm0 0h-6m-4 0h-.007m0 0A4 4 0 1 1 13 9v4m-4.007 0H13m0 0v6m0 0v4a4 4 0 1 1-4-4z"/></svg>
    );
}
