// ChevronUp.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing chevron-up.svg overwrites this file.
import type { SVGProps } from "react";

export default function ChevronUp(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-chevron-up" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M26 20L16 10L6 20"/></svg>
    );
}
