// Broadcast.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing broadcast.svg overwrites this file.
import type { SVGProps } from "react";

export default function Broadcast(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-broadcast" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 20.66a10 10 0 0 0 0-17.32M11 20.66a10 10 0 0 1 0-17.32m8 13.856a6 6 0 0 0 0-10.392m-6 10.392a6 6 0 0 1 0-10.392M13.09 26L16 18l2.91 8m-5.82 0L12 29m1.09-3h5.82M20 29l-1.09-3M18 12a2 2 0 1 0-4 0a2 2 0 0 0 4 0"/></svg>
    );
}
