// FolderOpen.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing folder-open.svg overwrites this file.
import type { SVGProps } from "react";

export default function FolderOpen(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-folder-open" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M4 26V8a2 2 0 0 1 2-2h6c3 0 3 3 5 3h7a2 2 0 0 1 2 2v2M4 26l3.783-12.294A1 1 0 0 1 8.739 13H26M4 26h19.523a2 2 0 0 0 1.911-1.412l3.168-10.294A1 1 0 0 0 27.646 13H26"/></svg>
    );
}
