// Hamburger.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing hamburger.svg overwrites this file.
import type { SVGProps } from "react";

export default function Hamburger(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-hamburger" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 8h22M5 16h22M5 24h22"/></svg>
    );
}
