// Compose.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing compose.svg overwrites this file.
import type { SVGProps } from "react";

export default function Compose(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-compose" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M27 5L17 15m0-10H8a3 3 0 0 0-3 3v16a3 3 0 0 0 3 3h16a3 3 0 0 0 3-3v-9"/></svg>
    );
}
