// ArrowUp.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing arrow-up.svg overwrites this file.
import type { SVGProps } from "react";

export default function ArrowUp(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-arrow-up" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 27V6m8 7l-8-8l-8 8"/></svg>
    );
}
