// SendStop.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing send-stop.svg overwrites this file.
import type { SVGProps } from "react";

export default function SendStop(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-send-stop" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m21 26l6-6m2-17L3 15l12 2.5M29 3L15 17.5M29 3l-4.375 11.375M15 17.5l.625 2.875M29 23a5 5 0 1 1-10 0a5 5 0 0 1 10 0"/></svg>
    );
}
