// Pin.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing pin.svg overwrites this file.
import type { SVGProps } from "react";

export default function Pin(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-pin" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m14 18l-8 8M20.667 4L28 11.333l-6.38 6.076a2 2 0 0 0-.62 1.448v3.729c0 .89-1.077 1.337-1.707.707L8.707 12.707c-.63-.63-.184-1.707.707-1.707h3.729a2 2 0 0 0 1.448-.62z"/></svg>
    );
}
