// Expand.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing expand.svg overwrites this file.
import type { SVGProps } from "react";

export default function Expand(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-expand" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m9 20l7 7l7-7m0-8l-7-7l-7 7"/></svg>
    );
}
