// FolderArchive.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing folder-archive.svg overwrites this file.
import type { SVGProps } from "react";

export default function FolderArchive(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-folder-archive" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 11h20m-14 5h8M5 7v4h2v14.002C7 26.106 7.895 27 9 27h14c1.105 0 2-.894 2-1.998V11h2V7a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2"/></svg>
    );
}
