// Lock.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing lock.svg overwrites this file.
import type { SVGProps } from "react";

export default function Lock(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-lock" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 24v-4m5-5V8a5 5 0 0 0-10 0v7M6 27V17a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2"/></svg>
    );
}
