// Off.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing off.svg overwrites this file.
import type { SVGProps } from "react";

export default function Off(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-off" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M22.5 4.742a13 13 0 1 1-13 0M16 3v10"/></svg>
    );
}
