// LoadingSpin.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing loading-spin.svg overwrites this file.
import type { SVGProps } from "react";

export default function LoadingSpin(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-loading-spin" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M22.5 4.742A13 13 0 1 0 29 16"/></svg>
    );
}
