// Mail.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing mail.svg overwrites this file.
import type { SVGProps } from "react";

export default function Mail(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-mail" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M29 9v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9m26 0a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2m26 0l-11.862 8.212a2 2 0 0 1-2.276 0L3 9"/></svg>
    );
}
