// Cloudia.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing cloudia.svg overwrites this file.
import type { SVGProps } from "react";

export default function Cloudia(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-cloudia" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><mask id="SVGhifbLbfL" fill="#fff"><path d="M12 18a2 2 0 1 1-4 0a2 2 0 0 1 4 0m10 0a2 2 0 1 1-4 0a2 2 0 0 1 4 0"/></mask><g fill="none"><path fill="currentColor" d="M12 18a2 2 0 1 1-4 0a2 2 0 0 1 4 0m10 0a2 2 0 1 1-4 0a2 2 0 0 1 4 0"/><path stroke="currentColor" strokeWidth="2" d="M12 18a2 2 0 1 1-4 0a2 2 0 0 1 4 0Zm10 0a2 2 0 1 1-4 0a2 2 0 0 1 4 0Z" mask="url(#SVGhifbLbfL)"/><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 21h-2m12.708-4.717a9 9 0 1 0-17.66-3.218A7.001 7.001 0 0 0 10 27h13a6 6 0 0 0 3.708-10.717"/></g></svg>
    );
}
