// Focus.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing focus.svg overwrites this file.
import type { SVGProps } from "react";

export default function Focus(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-focus" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><mask id="SVGbyN7QdEZ" fill="#fff"><path d="M10 16a3 3 0 1 1-6 0a3 3 0 0 1 6 0"/></mask><g fill="none" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d="M18 16a2 2 0 1 1-4 0a2 2 0 0 1 4 0m9 0a2 2 0 1 1-4 0a2 2 0 0 1 4 0"/><path fill="currentColor" d="M10 16a3 3 0 1 1-6 0a3 3 0 0 1 6 0Z" mask="url(#SVGbyN7QdEZ)"/></g></svg>
    );
}
