// Link.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing link.svg overwrites this file.
import type { SVGProps } from "react";

export default function Link(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-link" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m14.9 19.142l-.708-.707c-2.12-2.121-2.12-4.95 0-7.071l2.829-2.828c2.121-2.122 4.95-2.122 7.07 0c2.122 2.12 2.122 4.95 0 7.07m-6.363-2.12l.707.706c2.121 2.122 2.121 4.95 0 7.072l-2.828 2.828c-2.122 2.121-4.95 2.121-7.071 0c-2.122-2.121-2.122-4.95 0-7.071"/></svg>
    );
}
