// Catchup.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing catchup.svg overwrites this file.
import type { SVGProps } from "react";

export default function Catchup(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-catchup" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M23 27H7a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v6m0 14h2a2 2 0 0 0 2-2V15a2 2 0 0 0-2-2h-2m0 14V13M9 10h4m-4 7h10M9 21h6"/></svg>
    );
}
