// Share.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing share.svg overwrites this file.
import type { SVGProps } from "react";

export default function Share(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-share" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 17v8a2 2 0 0 0 2 2h18a2 2 0 0 0 2-2v-8m-11 3V3.5M22 9l-6-6l-6 6"/></svg>
    );
}
