// ToDo.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing to-do.svg overwrites this file.
import type { SVGProps } from "react";

export default function ToDo(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-to-do" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m11.5 16l3.5 3.5l6-6m8 2.5a13 13 0 1 1-26 0a13 13 0 0 1 26 0"/></svg>
    );
}
