// CalendarSomeday.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing calendar-someday.svg overwrites this file.
import type { SVGProps } from "react";

export default function CalendarSomeday(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-calendar-someday" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><mask id="SVG4FH3bcts" fill="#fff"><path d="M17.25 23.75a1.25 1.25 0 1 1-2.5 0a1.25 1.25 0 0 1 2.5 0"/></mask><g fill="none" stroke="currentColor" strokeWidth="2"><path fill="currentColor" d="M17.25 23.75a1.25 1.25 0 1 1-2.5 0a1.25 1.25 0 0 1 2.5 0Z" mask="url(#SVG4FH3bcts)"/><path strokeLinecap="round" strokeLinejoin="round" d="M14 17.462a2 2 0 1 1 2 2V20.5M5 12h22m-6-4V4M11 8V4M7 28h18a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2"/></g></svg>
    );
}
