// Calendar.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing calendar.svg overwrites this file.
import type { SVGProps } from "react";

export default function Calendar(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-calendar" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14.5 16.5h2V23M5 12h22m-6-4V4M11 8V4M7 28h18a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2"/></svg>
    );
}
