// ChevronRight.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing chevron-right.svg overwrites this file.
import type { SVGProps } from "react";

export default function ChevronRight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-chevron-right" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m12 26l10-10L12 6"/></svg>
    );
}
