// Search.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing search.svg overwrites this file.
import type { SVGProps } from "react";

export default function Search(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-search" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m5 27l7.5-7.5M28 13a9 9 0 1 1-18 0a9 9 0 0 1 18 0"/></svg>
    );
}
