// Forward.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing forward.svg overwrites this file.
import type { SVGProps } from "react";

export default function Forward(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-forward" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 13S3 13 3 16s14 3 14 3v3.453c0 1.74 2.069 2.65 3.351 1.475l7.04-6.454a2 2 0 0 0 0-2.948l-7.04-6.454C19.07 6.896 17 7.806 17 9.546z"/></svg>
    );
}
