// Breather.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing breather.svg overwrites this file.
import type { SVGProps } from "react";

export default function Breather(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-breather" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M25.192 25.192A13 13 0 1 0 6.808 6.808a13 13 0 0 0 18.384 18.384"/></svg>
    );
}
