// SendCancelled.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing send-cancelled.svg overwrites this file.
import type { SVGProps } from "react";

export default function SendCancelled(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-send-cancelled" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m20 19l4 4m0 0l4 4m-4-4l-4 4m4-4l4-4m1-16L3 15l12 2.5M29 3L15 17.5M29 3l-4.375 11.375M15 17.5l.625 2.875"/></svg>
    );
}
