// Warning.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing warning.svg overwrites this file.
import type { SVGProps } from "react";

export default function Warning(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-warning" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><mask id="SVG9i8vndUf" fill="#fff"><path d="M17.5 21.5a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0"/></mask><g fill="none" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" d="M16 18v-6M6.358 27h19.284c1.516 0 2.48-1.62 1.759-2.953l-9.642-17.8c-.757-1.397-2.761-1.397-3.518 0L4.6 24.047C3.877 25.38 4.842 27 6.358 27Z"/><path fill="currentColor" d="M17.5 21.5a1.5 1.5 0 1 1-3 0a1.5 1.5 0 0 1 3 0Z" mask="url(#SVG9i8vndUf)"/></g></svg>
    );
}
