// MailOpen.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing mail-open.svg overwrites this file.
import type { SVGProps } from "react";

export default function MailOpen(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-mail-open" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m4 8l9 7h6l9-7M15.118 3.271L3.706 6.783A1 1 0 0 0 3 7.739V23a2 2 0 0 0 2 2h22a2 2 0 0 0 2-2V7.739a1 1 0 0 0-.706-.956L16.882 3.27a3 3 0 0 0-1.764 0"/></svg>
    );
}
