// Pause.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing pause.svg overwrites this file.
import type { SVGProps } from "react";

export default function Pause(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-pause" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11.5 7v18m9-18v18"/></svg>
    );
}
