// MeatballsH.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing meatballs-h.svg overwrites this file.
import type { SVGProps } from "react";

export default function MeatballsH(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-meatballs-h" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeWidth="2" d="M8 17a1 1 0 1 0 0-2a1 1 0 0 0 0 2Zm8 0a1 1 0 1 0 0-2a1 1 0 0 0 0 2Zm8 0a1 1 0 1 0 0-2a1 1 0 0 0 0 2Z"/></svg>
    );
}
