// Label.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing label.svg overwrites this file.
import type { SVGProps } from "react";

export default function Label(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-label" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><g fill="none"><path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m10 19l5.5-5.5M13 22l2.5-2.5M4.414 16.586l11-11A2 2 0 0 1 16.828 5H25a2 2 0 0 1 2 2v8.172a2 2 0 0 1-.586 1.414l-11 11a2 2 0 0 1-2.828 0l-8.172-8.172a2 2 0 0 1 0-2.828"/><path fill="currentColor" d="M23 10a1 1 0 1 1-2 0a1 1 0 0 1 2 0"/></g></svg>
    );
}
