// ChevronDown.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing chevron-down.svg overwrites this file.
import type { SVGProps } from "react";

export default function ChevronDown(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-chevron-down" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m6 12l10 10l10-10"/></svg>
    );
}
