// Printer.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing printer.svg overwrites this file.
import type { SVGProps } from "react";

export default function Printer(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-printer" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M22 24h3a2 2 0 0 0 2-2V12a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h3m0-14V5h12v5M9 17h14m-13 0v10h12V17"/></svg>
    );
}
