// Checkmark.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing checkmark.svg overwrites this file.
import type { SVGProps } from "react";

export default function Checkmark(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-checkmark" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m6.5 17l6 6l13-13"/></svg>
    );
}
