// ForceBatch.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing force-batch.svg overwrites this file.
import type { SVGProps } from "react";

export default function ForceBatch(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-force-batch" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M24 15h1a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h1m6 4h4m-2-4V3m0 12l4-4m-4 4l-4-4"/></svg>
    );
}
