// settings.ts -- GENERATED by automation/icons/indexIcons.mjs
// `id` is intentionally blank: no db row exists yet. Whatever writes the row
// fills it in. `folder` is the folder NAME only -- the paths map holds where.
export const settings = {
    name: "user-sad",
    folder: "UserSad",
    file_name: "user-sad.svg",
    id: "",
};

export default settings;
