// CheckmarkDouble.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing checkmark-double.svg overwrites this file.
import type { SVGProps } from "react";

export default function CheckmarkDouble(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-checkmark-double" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m4 17l5 5l12-12m-5 10l2 2l12-12"/></svg>
    );
}
