// CalendarAdd.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing calendar-add.svg overwrites this file.
import type { SVGProps } from "react";

export default function CalendarAdd(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-calendar-add" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 23.5V20m0 0v-3.5m0 3.5h-3.5m3.5 0h3.5M5 12h22m-6-4V4M11 8V4M7 28h18a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2"/></svg>
    );
}
