// Download.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing download.svg overwrites this file.
import type { SVGProps } from "react";

export default function Download(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-download" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 22V5M9 16l7 7l7-7M9 27h14"/></svg>
    );
}
