// Escape.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing escape.svg overwrites this file.
import type { SVGProps } from "react";

export default function Escape(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-escape" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 23L23 9m0 14L9 9"/></svg>
    );
}
