// Collapse.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing collapse.svg overwrites this file.
import type { SVGProps } from "react";

export default function Collapse(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-collapse" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m23 26l-7-7l-7 7M9 6l7 7l7-7"/></svg>
    );
}
