// Clock.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing clock.svg overwrites this file.
import type { SVGProps } from "react";

export default function Clock(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-clock" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 8v8l4 4m9-4c0 7.18-5.82 13-13 13S3 23.18 3 16S8.82 3 16 3s13 5.82 13 13"/></svg>
    );
}
