// UserHappy.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing user-happy.svg overwrites this file.
import type { SVGProps } from "react";

export default function UserHappy(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-user-happy" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.5 23s1 1 2.5 1s2.5-1 2.5-1m4.5-5a1 1 0 1 1-2 0a1 1 0 0 1 2 0m-12 0a1 1 0 1 1-2 0a1 1 0 0 1 2 0m18-2c0 7.18-5.82 13-13 13S3 23.18 3 16S8.82 3 16 3s13 5.82 13 13"/></svg>
    );
}
