// Filter.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing filter.svg overwrites this file.
import type { SVGProps } from "react";

export default function Filter(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-filter" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 7h22M7 13h18M9 19h14m-12 6h10"/></svg>
    );
}
