// Alarm.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing alarm.svg overwrites this file.
import type { SVGProps } from "react";

export default function Alarm(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-alarm" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M26.607 6.392a15 15 0 0 0-6.725-3.882m-7.764 0a15 15 0 0 0-6.725 3.882M16 9v8l-4 4m15-4c0 6.075-4.925 11-11 11S5 23.075 5 17S9.925 6 16 6s11 4.925 11 11"/></svg>
    );
}
