// List.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing list.svg overwrites this file.
import type { SVGProps } from "react";

export default function List(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-list" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M12 8h15m-15 8h9m-9 8h15M7 24a1 1 0 1 1-2 0a1 1 0 0 1 2 0Zm0-8a1 1 0 1 1-2 0a1 1 0 0 1 2 0Zm0-8a1 1 0 1 1-2 0a1 1 0 0 1 2 0Z"/></svg>
    );
}
