// MailList.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing mail-list.svg overwrites this file.
import type { SVGProps } from "react";

export default function MailList(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-mail-list" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 7h14m4 0h4M5 13h10m8 0h4M5 19h14m4 0h4M5 25h12m6 0h4"/></svg>
    );
}
