// Stopwatch.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing stopwatch.svg overwrites this file.
import type { SVGProps } from "react";

export default function Stopwatch(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-stopwatch" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M27.9 7.869a15 15 0 0 0-2.769-2.77m-7.434-.988a13 13 0 0 0-3.394 0m12.304 2.282l-2.829 2.829M16 17l5 5m6-5c0 6.075-4.925 11-11 11S5 23.075 5 17S9.925 6 16 6s11 4.925 11 11"/></svg>
    );
}
