// Markdown.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing markdown.svg overwrites this file.
import type { SVGProps } from "react";

export default function Markdown(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-markdown" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 20v-8l-4 4l-4-4v8m12-3.5l3.5 3.5m0 0l3.5-3.5M22.5 20v-9M5 7h22a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2"/></svg>
    );
}
