// Skip.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing skip.svg overwrites this file.
import type { SVGProps } from "react";

export default function Skip(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-skip" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M23 5v22M8 7.586v16.828c0 1.746 2.081 2.653 3.36 1.465l9.062-8.413a2 2 0 0 0 0-2.932L11.36 6.121C10.08 4.933 8 5.84 8 7.586"/></svg>
    );
}
