// Desktop.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing desktop.svg overwrites this file.
import type { SVGProps } from "react";

export default function Desktop(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-desktop" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 27h4m-4 0l.5-4h3l.5 4m-4 0h-3m7 0h3M5 5h22a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2"/></svg>
    );
}
