// Eye.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing eye.svg overwrites this file.
import type { SVGProps } from "react";

export default function Eye(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-eye" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><g fill="none" stroke="currentColor" strokeLinejoin="round" strokeWidth="2"><path d="M29 16c0 3-5.82 9-13 9S3 19 3 16s5.82-9 13-9s13 6 13 9Z"/><path d="M21 16a5 5 0 1 1-10 0a5 5 0 0 1 10 0Z"/></g></svg>
    );
}
