// ArrowLeft.tsx -- GENERATED by automation/icons/indexIcons.mjs
// Do not hand-edit: re-indexing arrow-left.svg overwrites this file.
import type { SVGProps } from "react";

export default function ArrowLeft(props: SVGProps<SVGSVGElement>) {
    return (
        <svg className="icon icon-arrow-left" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" {...props}><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 16h21M13 8l-8 8l8 8"/></svg>
    );
}
